languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
title = "towry~blog"
baseurl = "//towry.me/"
themesDir = "themes"
theme = "reveal.hugo-theme"
staticDir = "static"
googleAnalytics = "UA-56790537-1"

[author]
  name = "Towry Wang"
  email = "tovvry#gmail.com"

[params]
  disqusShortname = "towry"
